exports.notFoundErrorMessage = 'Запрашиваемые данные не найдены';
exports.forbiddenErrorMessage = 'Нет прав для совершения этого действия';
exports.validationErrorMessage = 'Переданы некорректные данные';
exports.notUniqueErrorMessage = 'Пользователь с таким email уже существует.';
exports.typeErrorMessage = 'Данные должны быть';
exports.emailRequireErrorMessage = 'Необходимо ввести Email';
exports.emailValidateErrorMessage = 'Введен некорректный Email';
exports.passwordRequireMessage = 'Необходимо ввести пароль';
exports.linkValidateErrorMessage = 'Введена некорректная ссылка';
